### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by Rotaerk** [joelburget/assimp#8]
I'm thinking I'd like to use assimp from haskell.  I was considering writing some bindings, but then I noticed yours.  It hasn't been touched for years, and currently doesn't build, but it's a much better starting point than from scratch.

Would you be up for reviewing pull requests I send your way to bring this up to a usable state?  Alternatively, would you be willing to make me maintainer on hackage, perhaps after I've demonstrated satisfactory changes in a fork?

Also, was there a technical reason for you dropping this?  Did it turn out to be unnecessary for your needs, and you found an alternative solution?  Or was it just a case of lost interest/time?

**Comment by Rotaerk** [comment]
Actually, never mind.  I think I'll start a new package.  I am still interested in knowing if there was a technical reason you dropped this, though.

**Comment by joelburget** [comment]
Hi Rotaerk, there was no technical reason I dropped this, and it worked for simple cases, but I stopped working on my ray tracer project and moved on to other things. I'd be happy to see good Assimp bindings in Haskell -- good luck with your project!
